[data]
database_loc = "./data/ACS_convert"
tf_dataset_loc = "./data/tf"
id_col = "id_OpenAlex"
RAM_MAX = 4718592000
overwrite_tf_dataset = true
journal = "ACS"
n_features = 384
feature_col_name = "embedding_"
y_cols = ["higher_than_median_year"]
max_timepoints = 20
pad_value = 0.0
sort_col = "publication_date_int"
[data.range_vals]
publication_date_int_min = 1900
publication_date_int_max = 2024
publication_date_int_delta = 1

[model  ]
model_name = "cnn"
 
[train]
val_size = 5
test_size = 1
start_train_size = 90
CV_delta = 1
start_year = 1900
end_year = 2020
max_trials = 15
ratio_initial_points = 0.25
patience = 2

[log]
file = "ERROR"
console = "INFO" 
